name: Test

on:
  push:
    paths:
      - 'test/**'
      - 'src/**'
      - 'action.yml'
      - 'package.json'
  pull_request:
    paths:
      - 'test/**'
      - 'src/**'
      - 'action.yml'
      - 'package.json'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Test Action
        uses: ./
        with:
          repository: test
          path: './test/test-package_1.0.0_amd64.deb'
          nexus_url: http://${{ secrets.NEXUS_ENDPOINT }}
          nexus_user: ${{ secrets.NEXUS_USER }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }} 